### ISSUE TITLE
First parameter adjustments

### ISSUE THREAD

**Issue by ben-rogerson** [CupOfTea696/laravel-mix-imagemin#4]
hey there,

I'm wondering if it's possible to adjust the first parameter to more closely resemble the webpack-copy-plugin options.

Now in v1.0.2 when I use an object as shown in the webpack-copy-plugin docs I receive a multimatch error.

Here's my config:

```js
mix.imagemin(
    {
        from: 'src/images/**/*'),
        to: 'dist',
        flatten: true,
    },
    {},
    ...
},
```

Perhaps a backwards compatible fix would be to check if the first param is an object that has a `from` key and check that with multimatch instead, eg:
```js
multimatch(asset, this.patterns.from).length
```

**Comment by CupOfTea696** [comment]
This should be fixed in v1.0.3, let me know if there's anything else.
